### PR TITLE
Added two more LeetCode problems

### PR DESCRIPTION
**Pull request by adityap301**
**Added the <Filename> Filename as**
#231-Power_Of_Two.cpp
#342-Power_Of_Four.cpp

**Changes Proposed <Describe> in the PR. Describe**
Added the solutions to problems #231 and #342.
Runtime and memory usage is mentioned in the commits.

**I am assuring that the file is not redundant and making the Pull Request**
- [x] Yes

### CODE REVIEW

**Comment by adityap301** [comment]
Do let me know if there are any issues.

**Review by mansikagrawal — CHANGES_REQUESTED** [review]
Please write full code with main functions too with an explanation.

**Comment by adityap301** [comment]
> Please write full code with main functions too with an explanation.

Hey @mansikagrawal, LeetCode solutions do not require the main function as it is already provided by the IDE. One is just required to write the solution inside the Solution class provided by the LeetCode IDE. The other solutions that have been submitted to the repo follow a similar suite.

**Comment by adityap301** [comment]
I've done the requested changes. Do check and let me know.

**Comment by mansikagrawal** [comment]
Works. Please squash the commits .

**Comment by adityap301** [comment]
Commits have been squashed.

**Pull request merged**
